<?php
/**
* Load system-wide configuration settings
*
* Set up a config object that parses the { @link bumblebee.ini } file.
*
* @author    Stuart Prescott
* @copyright  Copyright Stuart Prescott
* @license    http://opensource.org/licenses/gpl-license.php GNU Public License
* @version    $Id$
* @package    Bumblebee
* @subpackage Misc
*/

/** Load ancillary functions */
require_once 'inc/typeinfo.php';
checkValidInclude();

require_once 'inc/bb/configreader.php';

$REBASE_INSTALL = isset($REBASE_INSTALL) ? $REBASE_INSTALL : '';
$NON_FATAL_CONFIG = isset($NON_FATAL_CONFIG) ? $NON_FATAL_CONFIG : false;

/*
* Set the location of config files
*
* By default, config/ in the Bumblebee installation directory, but
* can be moved into /etc, /usr/share/bumblebee ...
*/
$configLocation = $REBASE_INSTALL.'config/';

/**
* $CONFIG contains the parsed config options for this installation
* @global array $CONFIG
*/
global $CONFIG;

new ConfigReader();
$conf = & ConfigReader::getInstance();
$conf->SetFileLocation($configLocation);
$conf->LoadFile('bumblebee.ini');
$conf->ParseConfig();

$CONFIG = $conf->data;

/**
* $ADMINEMAIL is used for generating links to the administrator for more information, help etc
* @global string $ADMINEMAIL
*/
global $ADMINEMAIL;
$ADMINEMAIL = $CONFIG['main']['AdminEmail'];

/**
* $BASEPATH is the path to this installation so that CSS and image files can be found by the browser
* @global string $BASEPATH
*/
global $BASEPATH;
$BASEPATH   = $CONFIG['main']['BasePath'];
if (substr($BASEPATH, 0, 1) != '/' && ! $config_error) {
  // the first character of the path must be a slash
  // the user is never going to be able to log on when it's like this, so let's kill it off.
  trigger_error('Bumblebee misconfiguration: please make sure that the BasePath parameter in bumblebee.ini is only the path portion of the URL and does not include the server name. (Hint: should start with a "/" and be something like "/bumblebee" or "/departments/chemistry/equipment")', $NON_FATAL_CONFIG ? E_USER_NOTICE : E_USER_ERROR);
}

/**
* $BASEURL is prepended to all URLs generated by the system so that the links work
* @global string $BASEURL
*/
global $BASEURL;
$BASEURL    = $CONFIG['main']['BaseURL'];

/**
* Copyright of generated output is attributed to $COPYRIGHTOWNER
* @global string $COPYRIGHTOWNER
*/
global $COPYRIGHTOWNER;
$COPYRIGHTOWNER = $CONFIG['main']['CopyrightOwner'];


/**
* If $VERBOSESQL is true, then all SQL statements will be dumped to the browser for debugging purposes
* @global boolean $VERBOSESQL
*/
global $VERBOSESQL;
$VERBOSESQL = $CONFIG['error_handling']['VerboseSQL'];

/**
* If $VERBOSEDATA is true then user data will be dumped to the browser for debugging purposes
* @global boolean $VERBOSEDATA
*/
global $VERBOSEDATA;
$VERBOSEDATA = $CONFIG['error_handling']['VerboseData'];

ini_set("session.use_only_cookies",1); #don't permit ?PHPSESSID= stuff
#ini_set("session.cookie_lifetime",60*60*1); #login expires after x seconds


if (!empty($CONFIG['main']['ExtraIncludePath'])) {
  set_include_path($REBASE_INSTALL.$CONFIG['main']['ExtraIncludePath'].PATH_SEPARATOR.get_include_path());
}
if (isset($CONFIG['error_handling']['UseDBug']) && $CONFIG['error_handling']['UseDBug'] && ! $NON_FATAL_CONFIG) {
  // include the dBug pretty printer for error and debugging dumps
  // http://dbug.ospinto.com/
  include_once 'dBug.php';
}

if (! $NON_FATAL_CONFIG) {
  /** load the language pack */
  require_once 'i18n.php';

  // As of PHP5.0, we *must* set the timezone for date calculations, otherwise
  // many errors will be emitted. For a list of timezones, see
  //     http://php.net/manual/en/timezones.php
  $tz = isset($CONFIG['language']['timezone']) ? $CONFIG['language']['timezone'] : "Europe/London";
  date_default_timezone_set($tz);
}

/**
* $BUMBLEBEEVERSION is the installed version of the software
* @global string $BUMBLEBEEVERSION
*/
global $BUMBLEBEEVERSION;
$BUMBLEBEEVERSION = '1.1.5';

?>
